### ISSUE TITLE
Reproduce CVPR 2018 results

### ISSUE THREAD

**Issue by y0un5** [gtolias/asmk#2]
I executed the revisitop code using Octave (because I don't have Matlab), and got following results.

```
roxford5k: mAP E: 84.57, M: 67.90, H: 43.35
roxford5k: mP@k[1 5 10] E: [100.00 91.18 85.04], M: [98.57 94.00 88.29], H: [84.29 72.00 62.71]
​​
rparis6k: mAP E: 95.26, M: 77.25, H: 56.14
rparis6k: mP@k[1 5 10] E: [100.00 98.57 97.00], M: [100.00 100.00 99.14], H: [97.14 96.57 94.57]
```

Are these correct results? I don't know if Octave and Matlab might produces different results, so could you share your results using this code?

**Comment by gtolias** [comment]
>> roxford5k: mAP E: 84.28, M: 67.64, H: 42.98
>> roxford5k: mP@k[1 5 10] E: [98.53 90.29 85.50], M: [100.00 93.14 87.93], H: [87.14 70.57 61.79]

>> rparis6k: mAP E: 95.16, M: 76.85, H: 55.42
>> rparis6k: mP@k[1 5 10] E: [100.00 98.29 97.29], M: [100.00 100.00 99.29], H: [97.14 95.43 93.43]

Small differences are also due to the randomness of the binarization process.

**Comment by y0un5** [comment]
So, Octave result is not much different from Matlab's.
Thanks for your sharing!
